author/urls.py
from django.urls import path
from . import views

app_name = "author"
urlpatterns = [
    path("", views.BloggerListView.as_view(), name="all_authors"),
    path("<int:pk>", views.BloggerDetailView.as_view(), name="author_detail"),
    path("signup/", views.AuthorSignupView.as_view(), name="signup"),
    path(
        "login/",
        views.AuthorLogIn.as_view(template_name="author/login.html"),
        name="login",
    ),
    path("logout/", views.AuthorLogOut.as_view(), name="logout"),
]
# path('<int:pk>/profile/',views.AuthorRegisterForm.as_view(), name = 'author_profile')
# path('register/',views.AuthorRegisterView.as_view(),name = 'register'),

blog/urls.py
from django.urls import path
from . import views
from .views import BlogListView, BlogDetailView, HomeView, AddCommentView

app_name = "blog"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("blogs/", views.BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path(
        "blog/<int:pk>/add_comments", views.AddCommentView.as_view(), name="add_comment"
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("blogs/bloggers/", include("author.urls")),
]

blog/models.py
from django.db import models

from datetime import date
from django.utils.timezone import now
from author.models import Author
from django.contrib.auth.models import User
from django.conf import settings


class Blog(models.Model):
    title = models.TextField()
    content = models.TextField(default="")
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name="blogs", default=""
    )

    def __str__(self):
        return f"{self.title}"


class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    name = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None, related_name="created_comments"
    )
    comment = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, null=True)

    # def __str__(self):
    #     if len(self.comment) > settings.TRUNCATE_CHAR_LIMIT:
    #         return self.comment[:settings.TRUNCATE_CHAR_LIMIT] + "..."
    #     else:
    #         return self.comment
    # name = models.CharField(max_length=255)
    def __str__(self):
        return "%s" % (self.blog.title)

blog/forms.py
from django import forms
from .models import Comments


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        # fields = ("name", "comment")
        fields = ("comment",)
        # order_by = ("-date_added")

        widgets = {
            # "name": forms.TextInput(attrs={"class": "form-control"}),
            "comment": forms.Textarea(attrs={"class": "form-control"}),
        }

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Blog, Comments
from django.views.generic import TemplateView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from django.urls.base import reverse
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import Author
from django.http.response import Http404
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)


# Create your views here.


class HomeView(TemplateView):
    template_name = "home.html"


class BlogListView(ListView):
    model = Blog
    context_object_name = "blogs"
    template_name = "blog/blog_list.html"
    paginate_by = settings.DEFAULT_PAGINATED_RECORDS

    # def get_context_data(self, **kwargs)  :
    #     context = super(BlogListView,self).get_context_data(**kwargs)
    #     context['blogs'] = context['blogs'].order_by("-post_date")
    #     return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-post_date")  # Reorder the queryset
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog_details.html"
    context_object_name = "blog"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AddCommentView(LoginRequiredMixin, CreateView):
    template_name = "blog/add_comment.html"
    model = Comments
    # form_class = CommentForm
    fields = [
        "comment",
    ]
    # fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(AddCommentView, self).get_context_data(**kwargs)
        context["post"] = Blog.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        post = Blog.objects.get(id=self.kwargs["pk"])
        new_comment.name = self.request.user
        new_comment.blog = post
        new_comment.save(force_insert=True)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "blog:blog_detail",
            kwargs={
                "pk": self.kwargs["pk"],
            },
        )

    # success_url = reverse_lazy("blog:home")

blog/templates/blog/add_comment.html
{% extends "base.html" %}

{% block title %} Comment on Blog Post {% endblock %}

{% block content  %}



<div class = "form-group container">
    <h1>Add Comment</h1>
    <br><br>
 
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary"> Add Comments</button>
        {% comment %} <button  class="btn btn-secondary"> Add Comments</button> {% endcomment %}
    </form>
</div>

{% endblock content  %}

blog/templates/blog/blog_details.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="post">
    <div class="headline">
      <div class="title">
        <h1>{{ blog.title }}</h1>
        <div class="author">
          <p>Author: {{ blog.author }}</p>
          <p>{{blog.content}}</p>
          <p>{{ blog.post_date }}</p>
        </div>
      </div>
    </div>
  </div>
  <hr />
  <div class="container">
    <h1>Comments...</h1>
     
    {% if not blog.comments.all %} No comments Yet..
    <a href="{% url 'blog:add_comment' blog.id %}" style='color: blue'>Add One</a>
    {% comment %} <a href="#" style="color: blue">Add One</a> {% endcomment %}
     {% else %}
    <a href="{% url "blog:add_comment" blog.id%}">Add Comment</a><br><br>
    {% for comment in blog.comments.all %}
    <strong> {{ comment.name }} - {{ comment.date_added }} </strong><br />
    {{comment.comment}}
    <br /><br />


    {% endfor %} 
    <a href="{% url "blog:add_comment" blog.id%}">Add Comment</a>
    {% endif %} 
    <br>
  </div>
  <hr />

  {% endblock content %}
</div>

blog/templates/blog/blog_list.html
{% extends "base.html" %} {% block content %}

<div class="center">
  {% if blogs %}
  <div class="container">
    <h1>This is Blog Website</h1>

    {% for blog in blogs %}

    <div class="card mb-4">
      <div class="col-xs-4">
        <span class="pull-right font-weight-bold" style="margin-top: 10px">
          <h4>
            <a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a>
          </h4>
        
          <h6 class="row-1 text-truncate">{{blog.content}}</h6>
        </span>
      </div>
      <div class="text-right float-right mt-3">
        <figure class="text-end">
          <figcaption class="blockquote-footer">
            {% comment %} <cite title="Source Title">{{ blog.author }}</cite> {% endcomment %}
            <cite title="Source Title"><a href=" {% url "author:author_detail" blog.author_id %}">{{ blog.author.author_name }}</a></cite>
          </figcaption>
        </figure>
        <div class="icon-holder float-left">
          <i class="bi bi-chat ml-2"></i>
          <span>12 </span>
          <space></space>
          <i class="bi bi-calendar3 ml-2"></i>
          <span>{{blog.post_date}}</span>
        </div>
      </div>
    </div>

    {% endfor %} {% endif %}
  </div>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
  {% endblock content %}
</div>

blog/templates/blog/create_blog.html
{% extends "base.html" %}
{% block title %}New Blog{% endblock title %}
{% block content %}
<div class = "container">
    <h2>Create a new blog post</h2>
    <div >
        <form method="post">
        {% csrf_token %} 
        {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }} :</label><br />
                {{ field }}
            </div>
        {% endfor %}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>

{% endblock content %}