author/urls.py
from django.urls import path
from . import views

app_name = "author"
urlpatterns = [
    path("", views.BloggerListView.as_view(), name="all_authors"),
    path("<int:pk>", views.BloggerDetailView.as_view(), name="author_detail"),
    path("signup/", views.AuthorSignupView.as_view(), name="signup"),
    path(
        "login/",
        views.AuthorLogIn.as_view(template_name="author/login.html"),
        name="login",
    ),
    path("logout/", views.AuthorLogOut.as_view(), name="logout"),
]
# path('<int:pk>/profile/',views.AuthorRegisterForm.as_view(), name = 'author_profile')
# path('register/',views.AuthorRegisterView.as_view(),name = 'register'),

blog/urls.py
from django.urls import path
from . import views
from .views import BlogListView, BlogDetailView, HomeView, AddCommentView

app_name = "blog"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("blogs/", views.BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path(
        "blog/<int:pk>/add_comments", views.AddCommentView.as_view(), name="add_comment"
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("blogs/bloggers/", include("author.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Blog</title>
  </head>

  <body>
    <header class="header">
      <div>
        <nav
          class="navbar navbar-expand-lg navbar-light bg-light nav justify-content-end"
        >
          <a class="navbar-brand" href="{% url "blog:home" %}"
            ><span class="h4">BloggerZ Blog</span></a
          >
          <div class="nav justify-content-end">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <a class="nav-link" href="{% url "blog:home" %}"
                  >Home <span class="sr-only"></span
                ></a>
                <a class="nav-link" href=" {% url "blog:blog_list" %}">Blog </a>
                <a class="nav-link" href="{% url "author:all_authors" %}">Author</a>
                <a class="nav-link" href="{% url "author:signup" %}">About</a>
              </ul>
            </div>
            <button class="btn btn-outline-success" type="button"><a href="{% url "author:signup" %}">
              SignIn</a>
            </button>
            <button class="btn btn-sm btn-outline-secondary" type="button"><a href="{% url "author:logout" %}">
              SignOut</a>
            </button>
          </div>
        </nav>
      </div>
    </header>
    
    <main>
       {% comment %} <div class="containerBox">
        <div class="containerMo">
          <div class="boxMo">
            <div>
              {% comment %} <img src="{% static 'myproject/profile_avatars/Amrita_Pritam.jpg' %}" alt="hjkbfksdjb"> {% endcomment %}
            {% comment %} </div>
          </div>
          <div class="boxMo">123</div>
          <div class="boxMo">123</div>
          <div class="boxMo">123</div>
          <div class="boxMo">123</div>
        </div>
       </div>  {% endcomment %}
  
      {%block content %} 
      {% comment %} <div class="boxMo">
        <img src="{%static '/media/profile_avatars/1.png' %}" alt="" class="feature-image">
      </div> {% endcomment %}
      {%endblock content%}</main>
    <footer class="footer">
      <div class="container">
        <p>© Copyright {% now "Y" %} by BloggerZ Blog</p>
      </div>
    </footer>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}HOME{% endblock %}

{% block content %}
<div class="container">
    <div class="container text-center"><h1>Hello Readers!</h1></div>
<h2>About Blog app</h2>
<div class="p-3">
    <p>Welcome To Blog app.</p>
    <p>This website will let you read various blogs written by different authors. You can appreciate their work by writting comments below post and also you can write your own blog.</p>
    <p>Checkout some amazing posts....</p>
</div>
</div>
{% endblock %}