author/urls.py
from django.urls import path
from . import views

app_name = "author"
urlpatterns = [
    path("", views.BloggerListView.as_view(), name="all_authors"),
    path("<int:pk>", views.BloggerDetailView.as_view(), name="author_detail"),
    path("signup/", views.AuthorSignupView.as_view(), name="signup"),
    path(
        "login/",
        views.AuthorLogIn.as_view(template_name="author/login.html"),
        name="login",
    ),
    path("logout/", views.AuthorLogOut.as_view(), name="logout"),
]
# path('<int:pk>/profile/',views.AuthorRegisterForm.as_view(), name = 'author_profile')
# path('register/',views.AuthorRegisterView.as_view(),name = 'register'),

blog/urls.py
from django.urls import path
from . import views
from .views import BlogListView, BlogDetailView, HomeView, AddCommentView

app_name = "blog"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("blogs/", views.BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path(
        "blog/<int:pk>/add_comments", views.AddCommentView.as_view(), name="add_comment"
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("blogs/bloggers/", include("author.urls")),
]

author/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from PIL import Image


# class Author(models.Model):
class Author(models.Model):
    # author_user_name = models.CharField(max_length=50 )
    author_name = models.CharField(max_length=120)
    author_age = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(200)]
    )
    author_email = models.EmailField()
    author_bio = models.TextField(default="")
    author_profile_picture = models.ImageField(
        default="avatar.jpg", upload_to="profile_avatars"
    )

    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)

        # resize the image
        img = Image.open(self.author_profile_picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.author_profile_picture.path)

    def __str__(self):
        return self.author_name

author/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Author


class AuthorRegisterForm(UserCreationForm):
    class Meta:
        model = Author
        # fields = ('author_email','author_bio')
        fields = "__all__"


class AuthorSignupForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "input"

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

author/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, FormView, UpdateView
from .models import Author
from django.core.paginator import Paginator
from .forms import AuthorSignupForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, views, logout
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import Http404


# AuthorRegisterForm,


# Create your views here.
class BloggerListView(ListView):
    queryset = Author.objects.all()
    template_name = "author/all_bloggers.html"
    context_object_name = "authors"
    paginate_by = 10


class BloggerDetailView(DetailView):
    queryset = Author.objects.prefetch_related("blogs")
    template_name = "author/blogger_detail.html"
    context_object_name = "author"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_list = self.queryset.get(id=self.kwargs["pk"]).blogs.order_by("-post_date")

        # page_number = self.request.GET.get("page", 1)
        # page_size = self.request.GET.get("page_size", 3)
        # paginator = Paginator(blog_list, page_size)
        # page_obj = paginator.get_page(page_number)
        context["author_posts"] = blog_list
        return context


class AuthorSignupView(FormView):
    template_name = "author/register.html"
    form_class = AuthorSignupForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("blog:home")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("blog:blog_list")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)

        return super(AuthorSignupView, self).form_valid(form)


class AuthorLogIn(LoginView):
    redirect_authenticated_user = True

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        else:
            return reverse_lazy("blog:blog_list")

    def form_invalid(self, form):
        messages.error(self.request, "Invalid username or password")
        return self.render_to_response(self.get_context_data(form=form))


class AuthorLogOut(View):
    def get(self, request):
        logout(request)
        messages.success(request, f"You have been logged out.")
        return redirect("author:login")

author/templates/author/all_bloggers.html
{% extends "base.html" %}

{% block title %}List of bloggers{% endblock %}

{% block content %}
<div class = "container">
    <h1>All Bloggers</h1>
<hr>
<div>
    {% for author in authors %}
    <a href="{% url "author:author_detail" author.id %}" class="list-group-item list-group-item-action">{{ author.author_name }}</a><br>
    {% endfor %}
</div>

<nav>
  <div class="pagination justify-content-center mt-3">
      {% if page_obj.has_previous %}
          <a class="link-success mx-2" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
          <span>Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.<span>
      {% if page_obj.has_next %}
          <a class="link-success mx-2" href="?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
  </div>
</nav>
</div>
{% endblock %}


{% comment %} {% extends 'base.html' %}

{% block title %}List of bloggers{% endblock %}

{% block content %}
<h1>All Bloggers</h1>

{% if authors %}

    {% for author in authors %}

    <h4><a href="{% url "author:author_detail" author.id %}">{{author.author_name}}</a>  {{author.author_email}}</h4>
     
       
    
    {% endfor %}
{% endif %}


{% endblock %} {% endcomment %}

author/templates/author/blogger_detail.html
  {% extends "base.html" %} {% block content %}


<h2><p class ="text-center">{{author.author_name}}</p></h2>

 
 
<hr />
{% if author_posts %} {% for post in author_posts %}
<div class="container">
  <div class="card mb-4">
    <div class="col-xs-4">
      <span class="pull-right font-weight-bold" style="margin-top: 10px">
        <h4>
          <a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a>
        </h4>
      </span>
    </div>
    <div class="text-right float-right mt-3">
      <div class="icon-holder float-right">
        <i class="bi bi-chat ml-2"></i>
        <span>12 </span>
        <space></space>
        <i class="bi bi-calendar3 ml-2"></i>
        <span>{{post.post_date}}</span>
      </div>
    </div>
  </div>
</div>

{% endfor %} {% endif %} {% endblock content %}  



{% comment %} {% extends "base.html" %}

{% block title %}Author{% endblock %}

{% block content %}
<h1 class="text-success">{{author.author_name}}</h1>
<hr>
<div>
    <p>{{author.author_bio|linebreaksbr}}</p>
</div>
<hr>
<h3 class="text-success">All Blogs</h3>
{% if author_posts %}
{% for post in author_posts %}
<div class="card border-success m-3">
    <a class="text-decoration-none" href="{% url "blog:blog_detail" post.id %}"><h5 class="card-header bg-success text-white bg-opacity-75">{{ post.title }}</h5></a>
    { 
</div>
{% endfor %}
{% else %}
No blogs posted by {{author.author_name}} yet!
{% endif %}

<nav>
    <div class="pagination justify-content-center">
        {% if author_posts.has_previous %}
            <a class="link-success mx-2" href="?page={{ author_posts.previous_page_number }}">Previous</a>
        {% endif %}
            <span>Page {{author_posts.number}} of {{author_posts.paginator.num_pages}}.<span>
        {% if author_posts.has_next %}
            <a class="link-success mx-2" href="?page={{ author_posts.next_page_number }}">Next</a>
        {% endif %}
    </div>
  </nav>
{% endblock %} {% endcomment %}

author/templates/author/login.html
{% extends "base.html" %}

{% block content %}
{% if messages %}
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
{% endif %}
    <div class="container">
        <form method="post" action="{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}">
        {% csrf_token %}
        <h2>Login</h2>
        {{form.as_p}}
        <button type="submit">Login</button>
        <p>Don't have an account? <a href="{%url 'author:signup' %}">Register</a></p>
    </form>
</div>
{% endblock content %}
 
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/form.css' %}" />
</head> {% endcomment %}




{% comment %} {% extends "base.html" %} 

{% block title %}Sign Up{% endblock %} 

{% block content %}
<h2 class="text-center">Log in</h2>
<div class="mt-5 d-flex justify-content-center">
<form method="post">
    {% csrf_token %} 
    {% for field in form %}
        <div class="mb-3">
        <label class="form-label">{{ field.label }} :</label><br />
        {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Log in</button>
  </form>
</div>

{% endblock %} {% endcomment %}

author/templates/author/profile.html
{% extends "base.html" %}

{% block title %}User Profile{% endblock title %}

{% block content %}
<div class="row justify-content-between">
    <div class="col-5">
        <h2 class="text-success">Hello, {{user.author_name}}</h2>
    </div>
    <div class="col-4">
        <a href="{% url "author:author-profile-update" user.id %}" class="btn btn-success ms-3">Update Profile</a>
        <a href="{% url "blog:create-blog" %}" class="btn btn-success ms-3">Add Blog</a>
    </div>
</div>
<hr>
<div>
    <p>{{author.author_bio|linebreaksbr}}</p>
</div>
<hr>
<h3 class="text-success">All the blogs that you posted</h3>
{% if blogs %}
{% for blog in blogs %}
<div class="card border-success m-3">
    <div class="card-header bg-success bg-opacity-75 d-flex justify-content-between">
        <a class="text-decoration-none" href="{% url "blog:blog_detail" blog.id %}"><h5 class="text-white">{{ blog.title }}</h5></a>
        <div><a class="btn btn-outline-light btn-sm" href="{% url "blog:update-blog" blog.id %}">update</a>
        <a class="btn btn-outline-light btn-sm" href="{% url "blog:delete-blog" blog.id %}">delete</a></div>
    </div>
    <div class="card-body">
        {% comment %} <p class="card-text">Date posted :{{blog.created_at}}</p> {% endcomment %}
        <p class="card-text">Date posted :</p>
    </div>
</div>
{% endfor %}
{% else %}
You have not posted any blogs yet! <br> Add now....
{% endif %}
{% endblock content %}

author/templates/author/profile_update.html
{% extends "base.html" %}

{% block title %}Update{% endblock title %}

{% block content %}
<h1 class="text-success">Update your profile</h1>
<div class="row">
    <form action="{% url "author:author-profile-update" author.id %}" method='post'>
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label class="form-label">{{ field.label }} :</label><br>
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div> 
{% endblock content %}

author/templates/author/register.html
{% extends "base.html" %}

{% block content %}
 
<div class="container">
    <form method="POST" novalidate>
        {% csrf_token %}
        <h2>Sign Up</h2>

        {% for field in form %}
        <p>
            {% if field.errors %}
            <ul>
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
             {{ field.label_tag }} {{ field }}
        </p>
        {% endfor %}
        <button type="submit">Signup</button>
        <p>Already has an account? <a href="{% url "author:login" %}">Login</a></p>
    </form>
</div>

{% endblock content %}